name: Update GitHub Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Generate GitHub Contribution Snake
        run: npm run generate:snake

      - name: Configure Git
        run: |
          git config --global user.mqtias1812 "GitHub Actions"
          git config --global user.matias.torres@gmail.com "actions@github.com"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update GitHub Contribution Snake [skip ci]"
          git push

      - name: Update README.md
        run: |
          echo "![GitHub Contribution Snake Animation](https://raw.githubusercontent.com/${{ github.repository_owner }}/repository/output/github-contribution-grid-snake.svg)" > README.md

      - name: Commit and push README changes
        run: |
          git add README.md
          git commit -m "Update README.md [skip ci]"
          git push
